<p style="text-align: center; line-height: normal; margin: 15.0pt 0cm 7.5pt 0cm;"><strong><span style="font-family: Helvetica;">T&Eacute;RMINOS Y CONDICIONES</span></strong></p>
<p>T&Eacute;RMINOS Y CONDICIONES</p>

<p>Contrato de prestaci&oacute;n de servicios que celebran, por una parte Grupo OM Asen, S.C., que en lo sucesivo se denominar&aacute; &ldquo;EASY TAXES&rdquo;, a quien en lo sucesivo se le denominara como &ldquo;EL PRESTADOR DE SERVICIOS&rdquo;, y por la otra parte, el usuario de los servicios, a quien en lo sucesivo se le denominar&aacute; &ldquo;EL CLIENTE&rdquo;, conforme a las declaraciones y cl&aacute;usulas siguientes:</p>

<p>La sola utilizaci&oacute;n de dicha p&aacute;gina de Internet de nombre de dominio es www.easytaxes.com.mx, al igual que los aplicativos en su misma plataforma web propiedades de Grupo OM Asen, S.C., otorga al p&uacute;blico en general la condici&oacute;n de Cliente e implica la aceptaci&oacute;n, plena e incondicional, de todas y cada una de las condiciones generales y particulares incluidas en estos t&eacute;rminos y condiciones publicados en www.easytaxes.com.mx.</p>

<p>En caso de no aceptar en forma absoluta y completa los t&eacute;rminos y condiciones de este convenio, &ldquo;el Cliente&rdquo; deber&aacute; abstenerse de acceder y utilizar el sitio web www.easytaxes.com.mx.<br />
Cualquier modificaci&oacute;n a los presentes t&eacute;rminos y condiciones de uso ser&aacute; realizada cuando el titular de la misma, en este caso EASY TAXES, lo considere apropiado, siendo exclusiva responsabilidad del usuario asegurarse de tomar conocimiento de tales modificaciones.</p>

<p>D E C L A R A C I O N E S</p>

<p>I. DECLARA &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;:<br />
1. Que es una sociedad civil debidamente constituida de conformidad con las leyes de la rep&uacute;blica mexicana, situaci&oacute;n que se acredita con el acta constitutiva que para tal efecto se encuentra debidamente publicada dentro del sitio web www.easytaxes.com.mx.<br />
2. Que su Representante Legal, cuenta con las facultades necesarias para suscribir este instrumento, de conformidad con la escritura p&uacute;blica arriba se&ntilde;alada, y las cuales bajo protesta de decir verdad se manifiesta que no han sido revocadas ni modificadas en forma alguna a la fecha.<br />
3. Que su equipo profesional cuenta con la capacidad t&eacute;cnica y de conocimientos para la prestaci&oacute;n de los servicios profesionales que se le ofrecen al Cliente.</p>

<p>II. DECLARA &ldquo;EL CLIENTE&rdquo;:<br />
1. Que es una persona f&iacute;sica y/o moral con capacidad de goce y de ejercicio para la celebraci&oacute;n del presente acto, de acuerdo con las leyes vigentes en el lugar de su residencia. <br />
De igual manera manifiesta el cliente que es la misma persona f&iacute;sica y/o moral que se est&aacute; procediendo a registrar, o en su caso que es apoderado legal con poder u autorizaci&oacute;n notariada suficiente por parte de dicha persona f&iacute;sica para llevar acabo su contabilidad.<br />
2. Que es su voluntad contratar los servicios de contabilidad y facturaci&oacute;n que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; proporciona.<br />
3. Que utilizar&aacute; el sitio web y aplicativos proporcionados por &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, de conformidad con los t&eacute;rminos y condiciones establecidos en el presente contrato, por lo que se compromete a utilizarlo de conformidad con la ley, la moral, las buenas costumbres generalmente aceptadas, el orden p&uacute;blico y las pr&aacute;cticas generales en materia del uso de Internet y buenas practicas fiscales.<br />
4. Que se abstendr&aacute; de utilizar el servicio con fines il&iacute;citos, prohibidos en las leyes o disposiciones aplicables que pudieran resultar lesivos a los intereses de terceros, o del &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; o que de cualquier forma puedan da&ntilde;ar, inutilizar, sobrecargar o deteriorar los servicios, los equipos inform&aacute;ticos de otros usuarios de Internet (hardware y software), as&iacute; como realizar actos que pudieran alterar o vulnerar la seguridad de todos y cada uno de los elementos, aplicativos o herramientas electr&oacute;nicas proporcionadas por &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.<br />
5. Que los datos proporcionados a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; al momento del registro son ver&iacute;dicos y que en caso de que sufran modificaci&oacute;n alguna se lo har&aacute; saber a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.<br />
6. Que conoce las disposiciones que rigen los derechos y obligaciones de los contribuyentes, respecto a la emisi&oacute;n de CFDI contenidas en el C&oacute;digo Fiscal de la Federaci&oacute;n, entre otras las de sus art&iacute;culos 29 y 29-A, as&iacute; como las de la Resoluci&oacute;n Miscel&aacute;nea Fiscal y la p&aacute;gina de internet del SAT.<br />
7. Que es su voluntad libre y consiente autorizar a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; para que pueda enviar al SAT, las declaraciones y aclaraciones correspondientes entorno a su contabilidad, de conformidad con lo dispuesto por las disposiciones legales aplicables incluyendo las de Resoluci&oacute;n Miscel&aacute;nea Fiscal.<br />
8. Que conoce el aviso de privacidad y aviso legal de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; manifestando que est&aacute; de acuerdo con el mismo, y el cual se encuentra debidamente publicado dentro del sitio web www.easytaxes.com.mx.<br />
9. Que manifiesta que para los efectos del presente contrato la direcci&oacute;n que ha establecido como su lugar de residencia, su domicilio fiscal y su direcci&oacute;n de correo electr&oacute;nico son las que ha proporcionado con anterioridad a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, al momento de su registro de cuenta y.<br />
10. Que es su voluntad que las credenciales de acceso a su cuenta, sirvan para identificarlo, a efecto de que las mismas puedan ser consideradas como una Firma Electr&oacute;nica, bastante y suficiente para cualquier mensaje de datos enviado a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.</p>

<p>lll. DECLARAN AMBAS PARTES:</p>

<p>&Uacute;NICO. Que vistas las anteriores declaraciones, ambas partes se reconocen mutuamente la personalidad con la cual se ostentan, estando de acuerdo con obligarse en los t&eacute;rminos del presente Contrato al tenor de las siguientes:</p>

<p>C L &Aacute; U S U L A S</p>

<p>PRIMERA.- DESCRIPCION GENERAL DEL SERVICIO</p>

<p>&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se obliga a prestar a &ldquo;EL CLIENTE&rdquo;, a trav&eacute;s del sitio web y aplicativos, diversos servicios, los cuales contemplan distintos perfiles del mismo, pudiendo ser &uacute;nicamente de declaraci&oacute;n, o de facturaci&oacute;n por las ventas al p&uacute;blico en general de forma mensual, por lo que los servicios que se prestaran son los que &ldquo;EL CLIENTE&rdquo; designe y pague a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, las obligaciones por los perfiles que se contrate se sujetaran a los siguientes esquemas de planes:</p>

<p>SERVICIO: &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, en su modalidad de se obliga a prestar los siguientes servicios de forma mensual:<br />
1) Declaraci&oacute;n de Impuestos.<br />
2) Asesor&iacute;a telef&oacute;nica ilimitada.<br />
3) 5 folios para expedici&oacute;n de facturas personalizadas.<br />
4) Notificaciones Fiscales.<br />
5) Recordatorios mensuales a trav&eacute;s de correo electr&oacute;nico y/o via SMS.<br />
7) Acceso a revista electr&oacute;nica (Blog).</p>

<p>De igual manera ambas partes acuerdan en que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, no ser&aacute; responsable en ning&uacute;n momento y bajo ninguna circunstancia de lo siguiente:<br />
1) De la informaci&oacute;n que &ldquo;EL CLIENTE&rdquo; en su momento le facilite a EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, para la prestaci&oacute;n de los servicios contratados por parte de &ldquo;EL CLIENTE&rdquo;.<br />
2) De las posibles cartas invitaci&oacute;n que le pudiesen llegar a &ldquo;EL CLIENTE&rdquo;, con motivo y derivado de la prestaci&oacute;n de los servicios contratados.<br />
3) De las posibles auditorias, requerimientos, multas o cr&eacute;ditos fiscales, practicadas y/o interpuestas por parte de la autoridad fiscal o administrativa, que le pudiesen llegar a &ldquo;EL CLIENTE&rdquo;, con motivo y derivado de la prestaci&oacute;n de los servicios contratados.</p>

<p>SEGUNDA.- SUSCRIPCI&Oacute;N MENSUAL, COBRO Y FACTURACI&Oacute;N.</p>

<p>Pruebas gratis.- La Suscripci&oacute;n Mensual del servicio puede comenzar con una prueba gratuita por un periodo de 30 (treinta) d&iacute;as, o cualquier otra seg&uacute;n se indique en las promociones vigentes al momento de la contrataci&oacute;n. En cualquier caso, el periodo de prueba gratis no ser&aacute; aplicable junto con cualquier otra promoci&oacute;n que se ofrezca en el momento de contrataci&oacute;n, salvo en los casos y promociones que as&iacute; lo determine &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; de manera espec&iacute;fica. Si &ldquo;EL CLIENTE&rdquo; es o ha sido titular o usuario de alguna cuenta en los &uacute;ltimos 12 meses, no podr&aacute; recibir una prueba gratis.</p>

<p>&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; empezar&aacute; a cobrar el cargo de la Suscripci&oacute;n Mensual al completarse el periodo de prueba gratuito, a menos de que &ldquo;EL CLIENTE&rdquo; cancele su suscripci&oacute;n mensual antes de que termine dicho periodo de prueba gratuito. &ldquo;EL CLIENTE&rdquo; deber&aacute; cancelar su suscripci&oacute;n mensual en caso de que ya no desee contar con el acceso al servicio contratado. Para visualizar los detalles espec&iacute;ficos de su cuenta, asi como el precio de la misma, deber&aacute; visitar el Sitio Web y/o App y hacer clic en &quot;Mi Cuenta&quot;.</p>

<p>Si Usted desea cancelar su Cuenta, por favor haga clic en &quot;Mi Cuenta&quot; en el Sitio y siga las instrucciones que ah&iacute; se establecen, o bien, podr&aacute; solicitar asistencia para poder realizar la cancelaci&oacute;n v&iacute;a telef&oacute;nica.</p>

<p>Usted no recibir&aacute; un aviso de parte de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; inform&aacute;ndole que su periodo de prueba gratis finaliz&oacute; o que el per&iacute;odo con cargo de su Suscripci&oacute;n Mensual y/o Anual seg&uacute;n sea el caso comenz&oacute;. &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; continuar&aacute; cobrando el cargo de su Suscripci&oacute;n Mensual y/o Anual a trav&eacute;s de la forma de pago elegida hasta que se cancele por parte de &ldquo;EL CLIENTE&rdquo; el servicio contratado.</p>

<p>Al iniciar la suscripci&oacute;n en algunas de las modalidades de servicios ofrecidas por parte de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, &ldquo;EL CIIENTE&rdquo; acepta expresamente en que se le realicen los cobros por la prestaci&oacute;n del servicio contratado de acuerdo con la tarifa vigente en ese momento, a trav&eacute;s de la Forma de Pago que &ldquo;EL CLIENTE&rdquo; en su momento registr&oacute;, o bien, mediante la forma de pago que &ldquo;EL CLIENTE&rdquo; en su momento haya modificado. En caso de que &ldquo;EL CLIENTE&rdquo; requiera factura de la Suscripci&oacute;n Mensual y/o Anual por el servicio contratado, deber&aacute; solicitarlo a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.</p>

<p>Formas de pago aceptadas &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;:</p>

<p>1) Tarjetas de cr&eacute;dito.<br />
2) Tarjetas de d&eacute;bito.<br />
3) PayPal.</p>

<p>Los precios vigentes de la Suscripci&oacute;n Mensual podr&aacute;n ser modificados en cualquier momento por &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, o bien, se podr&aacute;n agregar nuevos precios de tiempo en tiempo. Si desea utilizar otra Forma de Pago o si hay alguna modificaci&oacute;n en la Forma de Pago, por ejemplo, respecto de la fecha de vencimiento o la validez de su tarjeta de cr&eacute;dito o d&eacute;bito, deber&aacute; modificar la informaci&oacute;n correspondiente a la Forma de Pago visitando el Sitio y haciendo clic en el v&iacute;nculo &quot;Mi Cuenta&quot;. Si se produce el vencimiento de su Forma de Pago sin que haya modificado la informaci&oacute;n de su Forma de Pago o dado de baja su Cuenta, por este medio &ldquo;EL CLIENTE&rdquo; reconoce que seguir&aacute; siendo responsable por todos los montos pendientes de pago. </p>

<p>Por &uacute;ltimo, en caso de que la forma de pago dada por &ldquo;EL CLIENTE&rdquo; al momento de la contrataci&oacute;n de servicio, por alguna raz&oacute;n sea necesario actualizarla, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se compromete a otorgarle a &ldquo;EL CLIENTE&rdquo;, un periodo de un mes de gracia a partir del vencimiento de la forma pago, para que &ldquo;EL CLIENTE&rdquo; actualice dicha informaci&oacute;n. </p>

<p>TERCERA.- DISPONIBILIDAD EN EL SERVICIO.<br />
El sitio web y aplicativos tendr&aacute;n una disponibilidad las 24 horas del d&iacute;a, excepto trat&aacute;ndose del servicio de asesor&iacute;a fiscal telef&oacute;nica o cualquier otra que requiera de una respuesta para &ldquo;El cliente&rdquo; ya que esto depender&aacute; del horario de atenci&oacute;n que ser&aacute; de Lunes a Viernes de 9:00 a 19:00 horas en d&iacute;as h&aacute;biles.<br />
Sin perjuicio de lo anterior, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, se reserva el derecho de realizar las mejoras y el mantenimiento continuo de la infraestructura del sitio web y aplicativos, en cualquier momento, de igual forma &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, podr&aacute; planear y ejecutar mantenimientos, con una duraci&oacute;n m&aacute;xima de 48horas, y de las cuales podr&aacute; notificar a &ldquo;EL CLIENTE&rdquo; con anterioridad a su ejecuci&oacute;n, en los t&eacute;rminos que establezcan las disposiciones de car&aacute;cter general aplicables y vigentes.<br />
En ning&uacute;n caso &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; ser&aacute; responsable para con &ldquo;EL CLIENTE&rdquo; por qu&eacute; la p&aacute;gina no est&eacute; disponible, ya sea por causas no imputables a &eacute;l o bien por mantenimiento requerido, por lo que &ldquo;EL CLIENTE&rdquo; no podr&aacute; realizar ning&uacute;n tipo de reclamaciones a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; deslind&aacute;ndolo desde este momento de cualquier responsabilidad.</p>

<p>CUARTA.- DE LAS CUENTAS DE USUARIO.<br />
Es voluntad de las partes pactar que para que &ldquo;EL CLIENTE&rdquo; pueda iniciar sesi&oacute;n en el sitio web y aplicativos, deber&aacute; de crear y registrar en la base de datos de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; una cuenta de usuario, siguiendo, para tal efecto, el procedimiento establecido. La primera cuenta de usuario que el Cliente cree y registre en la base de datos de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; ser&aacute; considerada la cuenta maestra administradora y ser&aacute; identificada como cuenta de administrador, dicha cuenta tendr&aacute; acceso a todas y cada una de las funcionalidades permitidas, en cualquiera de los servicios contratados y antes mencionados.<br />
Las cuentas de usuario de &ldquo;EL CLIENTE&rdquo; se conformar&aacute;n por un nombre de usuario, una contrase&ntilde;a y el n&uacute;mero de RFC del cliente, elementos que en su conjunto ser&aacute;n denominados como Claves de Acceso para los efectos del presente contrato. Las partes acuerdan que el uso de las Claves de Acceso, es absoluta y entera responsabilidad del cliente por lo que este deber&aacute; de resguardarlas en un lugar seguro, debiendo hacer un uso diligente de las mismas, as&iacute; como a no ponerlas a disposici&oacute;n de terceros, oblig&aacute;ndose a comunicar a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; cualquier situaci&oacute;n que pudiera comprometer la seguridad de dichas Claves de Acceso, como pueden ser la p&eacute;rdida o extrav&iacute;o de las mismas, obtenci&oacute;n de las mismas por una persona no autorizada y/o olvido, p&eacute;rdida o extrav&iacute;o de la contrase&ntilde;a o contrase&ntilde;as que conforman dichas Claves de Acceso de manera inmediata. El cliente acepta al registrarse y por su propia seguridad que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; cambie el Password para ingresar al portal del SAT, mismo que le ser&aacute; enviado al correo electr&oacute;nico con el que se registr&oacute;. Esto con el objetivo de brindar mayor seguridad al Cliente.<br />
Las partes acuerdan que es condici&oacute;n suspensiva para la prestaci&oacute;n de los servicios estipulados en el presente contrato que el cliente inicie sesi&oacute;n en el sitio web y aplicativos, siguiendo los procesos y procedimientos tecnol&oacute;gicos que se establecen el sitio web y aplicativos, para tal efecto.<br />
&ldquo;EASY TAXES&rdquo; no ser&aacute; responsable bajo ninguna circunstancia por el uso indebido de las claves de acceso que tenga en su poder &ldquo;EL CLIENTE&rdquo; por lo que este ser&aacute; &uacute;nico responsable por las gestiones que se realicen en el uso de dichas claves de acceso, deslindando a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; de cualquier tipo de responsabilidad.</p>

<p></p>

<p>
QUINTA.- SUSPENSI&Oacute;N DE CUENTA DE USUARIO.<br />
&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; suspender cualquiera o todas las cuentas de un usuario de &ldquo;EL CLIENTE&rdquo;, sin ning&uacute;n tipo de responsabilidad por las causas siguientes:</p>

<p>a) Si &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; detecta a trav&eacute;s de sus sistemas, que con el uso de la cuenta de usuario del cliente se est&aacute; llevando a cabo actividades il&iacute;citas, ilegales o delictivas;<br />
b) Si &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; detecta a trav&eacute;s de sus sistemas, que con el uso de la cuenta de usuario del cliente est&aacute; realizando alg&uacute;n da&ntilde;o a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, cualquiera de sus aplicativos, software, programas de c&oacute;mputo, hardware, infraestructura, equipos de c&oacute;mputo o cualquier otro elemento de naturaleza similar o an&aacute;loga, o bien est&aacute; realizando a alg&uacute;n da&ntilde;o a cualquier otro usuario o cliente de los servicios que presta o realice actos tendientes a causar un da&ntilde;o a cualquier persona;<br />
c) Si el cliente se lo solicita a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; expresamente;<br />
d) En caso de que el cliente no inicie sesi&oacute;n, en su cuenta de usuario en un periodo de 12 meses contados a partir de la &uacute;ltima fecha en que el cliente inici&oacute; sesi&oacute;n en su cuenta;<br />
e) Si &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; detecta, a trav&eacute;s de sus sistemas que existe un comportamiento anormal en la cuenta de usuario del cliente o si presume que la misma ha sido violentada por un tercero y;<br />
f) Por cualquier situaci&oacute;n de naturaleza similar o an&aacute;loga a alguna de las enlistadas con anterioridad, as&iacute; como falta de pago del servicio respectivo, para poder resolver la incidencia que dio origen a la suspensi&oacute;n de la cuenta. &ldquo;EL CLIENTE&rdquo;, deber&aacute; aclarar la situaci&oacute;n que dio origen a la suspensi&oacute;n de su cuenta de usuario a satisfacci&oacute;n de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; en un periodo de 30 d&iacute;as naturales, en caso contrario &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; cancelar la cuenta de usuario del cliente sin responsabilidad para &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.</p>

<p>SEXTA.- CANCELACI&Oacute;N DE LA CUENTA DE USUARIO.<br />
&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; cancelar cualquiera o todas las cuentas de un usuario del cliente, sin responsabilidad alguna, si &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; detecta que el sitio web y aplicativos est&aacute;n siendo utilizados con fines il&iacute;citos, delictivos o ilegales. De igual forma &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; cancelar la cuenta de usuario, si detecta que a trav&eacute;s de dicha cuenta de usuario se est&aacute;n realizando actos o actividades tendientes a violentar la seguridad tecnol&oacute;gica de las bases de datos propiedad de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;. As&iacute; mismo &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; cancelar la cuenta de usuario del cliente en caso de que opere la rescisi&oacute;n o terminaci&oacute;n anticipada del presente contrato seg&uacute;n lo que se establece en el presente.<br />
En caso de cancelaci&oacute;n de una cuenta de usuario, los datos personales de &ldquo;EL CLIENTE&rdquo; ser&aacute;n cancelados, estableci&eacute;ndose un periodo de bloqueo sobre ellos, de conformidad con la Ley de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares.<br />
&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; acceder el procedimiento de Devoluciones siempre cuando cumpla con lo establecido en los t&eacute;rminos, se deber&aacute; presentar el IFE de la persona que hizo el pago y tambi&eacute;n el IFE de la persona que se est&aacute; realizando su contabilidad junto con una carta libre firmada pidiendo su devoluci&oacute;n, despu&eacute;s de la recepci&oacute;n de los documentos tardara un plazo no mayor a 30 d&iacute;as h&aacute;biles para su devoluci&oacute;n en el banco.</p>

<p>SEPTIMA.- USO DEL SITIO WEB Y APLICATIVOS.<br />
&ldquo;EL CLIENTE&rdquo; se obliga a usar y acceder al sitio web y aplicativos, de un modo que no viole derechos de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; ni de terceros y respetando en todo momento la legislaci&oacute;n y disposiciones legales aplicables y vigentes en la Rep&uacute;blica Mexicana. &ldquo;EL CLIENTE&rdquo; no podr&aacute; utilizar el sitio web y aplicativos, con fines il&iacute;citos, ilegales o delictivos.<br />
Es voluntad de las partes establecer que el cliente tiene estrictamente prohibido:<br />
a) Modificar, sustituir, cambiar o en forma alguna alterar el contenido, textos, dibujos, dise&ntilde;os, programaci&oacute;n, lenguaje de programaci&oacute;n y en general alterar en forma sustancial o accesoria cualquier componente o programaci&oacute;n del sitio web y aplicativos;<br />
b) Limitar, bloquear, impedir o en cualquier forma restringir el acceso del sitio web y aplicativos;<br />
c) Guardar copia o copiar, en su computadora o de terceros, o en cualquier medio &oacute;ptico, electr&oacute;nico o de naturaleza similar o an&aacute;loga, cualquier elemento, dibujo, dise&ntilde;o, marca, o nombre comercial contenido o desplegado del sitio web y aplicativos;<br />
d) Hackear, Crackear o violentar o de cualquier forma obtener acceso no autorizado el sitio web y aplicativos, o accesar a trav&eacute;s de, &eacute;l o los servidores de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; con el objetivo de realizar cualquier actividad l&iacute;cita sin consentimiento expreso y por escrito de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; o il&iacute;cita, ilegal o delictiva, en ning&uacute;n caso, como puede ser robo o supresi&oacute;n de informaci&oacute;n;<br />
e) Obtener acceso de forma ilegal o no autorizada a los servicios que presta &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, a trav&eacute;s del sitio web y aplicativos.<br />
f) Editar o modificar el material del sitio web y aplicativos;<br />
g) Colocar el contenido del sitio web y aplicativos en noticias de grupo, correos electr&oacute;nicos de grupo, en carteles de anuncios, redes sociales, o en general cualquier otro sitio de naturaleza similar o an&aacute;loga;<br />
h) Utilizar el sitio web y aplicativos, identific&aacute;ndose como personal autorizado de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; y con ello actuar en su nombre;<br />
i) En general cualquier otro acto de naturaleza similar o an&aacute;loga que pueda afectar derechos de terceros o de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.<br />
Est&aacute; expresamente acordado por las partes, que si &ldquo;EL CLIENTE&rdquo; incurre en alguna de las conductas enumeradas en el p&aacute;rrafo anterior o en la presente cl&aacute;usula, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; tendr&aacute; la facultad de rescindir el presente contrato sin necesidad de declaraci&oacute;n judicial o administrativa para tal efecto, sin responsabilidad para &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; por lo que el cliente no podr&aacute; reclamar ning&uacute;n tipo de indemnizaci&oacute;n bajo ning&uacute;n concepto, sin embargo &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; si podr&aacute; reclamar una indemnizaci&oacute;n de conformidad con el presente contrato.</p>

<p>&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se reserva el derecho a modificar unilateralmente, en cualquier momento y sin aviso previo, la presentaci&oacute;n y configuraci&oacute;n del sitio web y aplicativos, as&iacute; como los Servicios y las condiciones requeridas para utilizar el mismo.</p>

<p>OCTAVA.- PUBLICIDAD EN EL SITIO WEB.<br />
&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se reserva el derecho de poner o incluir cualquier tipo de publicidad en el sitio web y aplicativos, como pueden ser elementos como im&aacute;genes, videos, banners, animaciones o cualquier otro elemento de naturaleza similar o an&aacute;loga.</p>

<p>NOVENA.- INFORMACION CONTABLE Y FISCAL VERIDICA.<br />
&ldquo;EL CLIENTE&rdquo; acepta que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; es una herramienta para el cumplimiento de obligaciones fiscales dentro del territorio Mexicano y que la informaci&oacute;n contable y fiscal de los ingresos y gastos que proporcione a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; es totalmente ver&iacute;dica, real, actual, o cierta y confirmada por &ldquo;EL CLIENTE&rdquo;, en caso de que &ldquo;EL CLIENTE&rdquo; haya declarado falsamente la informaci&oacute;n requerida ser&aacute; el &uacute;nico responsable por dicha situaci&oacute;n.</p>

<p>DECIMA.- POL&Iacute;TICAS DE PRIVACIDAD.<br />
&ldquo;EL CLIENTE&rdquo; deber&aacute; respetar las POL&Iacute;TICAS DE PRIVACIDAD establecidas en el presente contrato as&iacute; como en el documento denominado como AVISO DE PRIVACIDAD el cual se encuentra a su disposici&oacute;n en el sitio web y aplicativos y que ha sido puesto a su disposici&oacute;n con anterioridad y a trav&eacute;s del cual &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se compromete a asegurar la confidencialidad de la Informaci&oacute;n y Privacidad de la Informaci&oacute;n Personal que se obtiene de &ldquo;EL CLIENTE&rdquo; a trav&eacute;s de sus servicios en l&iacute;nea. El AVISO DE PRIVACIDAD, formar&aacute; parte integrante del presente contrato en su totalidad, y &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se obliga a cumplir con lo establecido en dicho documento en materia de Protecci&oacute;n de sus Datos Personales.<br />
Asimismo &ldquo;EL CLIENTE&rdquo; se obliga a guardar la entera confidencialidad y a la no divulgaci&oacute;n de datos, propiedad de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; o que se encuentren establecidos en el sitio web y aplicativos, por un t&eacute;rmino indefinido, obligaci&oacute;n que subsistir&aacute; aun cuando el presente contrato haya terminado su vigencia. &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se reserva el derecho de ejercer las acciones o derechos en contra de &ldquo;EL CLIENTE&rdquo; o de terceros, si alg&uacute;n acto es realizado en contravenci&oacute;n de lo establecido en esta cl&aacute;usula.</p>

<p>DECIMA PRIMERA.- PROPIEDAD INTELECTUAL.<br />
Es voluntad de las partes pactar que &ldquo;EL CLIENTE&rdquo; deber&aacute; respetar en todo momento los derechos de Propiedad Intelectual y/o Industrial que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; tenga, sobre obras como pueden ser Software, programas de c&oacute;mputo y/o aplicativos web; sobre marcas, nombres comerciales, patentes, secretos industriales y en general cualquier derecho inherente a la propiedad Intelectual y/o Industrial propiedad de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; a las cuales &ldquo;EL CLIENTE&rdquo; llegue a tener acceso, por virtud del presente contrato, por el uso del sitio web y aplicativos, o en general por cualquier otra raz&oacute;n. Por tal virtud &ldquo;EL CLIENTE&rdquo; se obliga, a no vulnerar los mencionados derechos de propiedad Intelectual o Industrial de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.<br />
De igual manera, las eventuales referencias que se hagan en esta p&aacute;gina a cualquier producto, servicio, proceso, sitio enlazado, hipertexto o cualquier otra informaci&oacute;n en la que se utilicen marcas, signos distintivos y/o dominios, el nombre comercial o el nombre del fabricante, suministrador, etc., que sean titularidad de terceros, en ning&uacute;n momento constituir&aacute;n, ni implicar&aacute;n respaldo o recomendaci&oacute;n alguna por parte de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; y en ning&uacute;n caso &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se asignan propiedad ni responsabilidad sobre los mismos.<br />
Mediante el uso de esta p&aacute;gina, el usuario reconoce y acepta que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, quedan excluidas de cualquier responsabilidad que pudiera ser causada por el uso no autorizado de las marcas u otros derechos de propiedad intelectual de terceros o contenidos en los sitios enlazados.<br />
&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se reserva en todo momento el derecho de ejercer las acciones penales, mercantiles o civiles, o cualquier otra cualquiera sea su naturaleza, en contra de &ldquo;EL CLIENTE&rdquo; por cualquier acto que pudiera ir en contravenci&oacute;n directa o indirecta a la presente cl&aacute;usula o en general contra cualquier acci&oacute;n que viole los derechos de propiedad Intelectual y/o Industrial de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;. Cualquier contravenci&oacute;n a esta cl&aacute;usula dar&aacute; lugar a la rescisi&oacute;n inmediata del mismo y har&aacute; acreedor a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; al pago de los da&ntilde;os y perjuicios en su favor estipulados en el presente contrato.<br />
Las partes acuerdan por virtud de este acto, que &ldquo;EL CLIENTE&rdquo; otorga una licencia de uso, gratuita y no exclusiva a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; sobre cualquiera de los logotipos, marcas, dise&ntilde;os, nombres comerciales, avisos comerciales, o cualquier otro elemento de propiedad Industrial, de naturaleza similar o an&aacute;loga que &ldquo;EL CLIENTE&rdquo; le proporcione a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; a trav&eacute;s del sitio web y aplicativos, con el objetivo de que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; haga uso de los mencionados elementos de propiedad Industrial, en cualquier material publicitario de sus productos o servicios, en cualquier medio, ya sea f&iacute;sico, impreso o electr&oacute;nico (incluido en el sitio web y aplicativos), &uacute;nica y exclusivamente para hacer menci&oacute;n de su cartera o listado de clientes, refiriendo en dichos materiales a &ldquo;EL CLIENTE&rdquo; como cliente de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.</p>

<p>DECIMA SEGUNDA.- LICENCIA DE SOFTWARE.</p>

<p>El Software y las funcionalidades pueden variar o diferir seg&uacute;n el dispositivo utilizado, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; le otorga a &ldquo;EL CLIENTE&rdquo; el Software bajo licencia gratuita y limitada al uso personal de conformidad con lo se&ntilde;alado en el presente contrato. &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; NO GARANTIZA EL DESEMPE&Ntilde;O DEL SOFTWARE, NI SU COMPATIBILIDAD CON LOS DIFERENTES DISPOSITIVOS. &ldquo;EL CLIENTE&rdquo; no puede copiar ni reproducir el Software, ni descompilar, realizar ingenier&iacute;a diversa, desarmar, modificar y/o crear cualquier otro sistema, programa u obra derivada basada en el Software o en una parte del Software. Todo uso no autorizado del Software queda estrictamente prohibido, por lo que en dado caso &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; se reserva el derecho de no proveerle a &ldquo;EL CLIENTE&rdquo; el Software (ni sus actualizaciones) en cualquier momento y de bloquear el acceso a su cuenta a trav&eacute;s del Software en cualquier momento.</p>

<p>&ldquo;EL CLIENTE&rdquo; reconoce y acuerda cumplir con los t&eacute;rminos de este contrato y con las modificaciones que de tiempo en tiempo se realicen al mismo, y recibir las versiones actualizadas del Software y de terceros relacionados. Si no acepta estas condiciones, reconoce que no utilizar&aacute; ni instalar&aacute; el Software.</p>

<p>&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; no garantiza que el Software sea compatible con software de terceros, ni que el funcionamiento del Software no da&ntilde;ar&aacute; ni afectar&aacute; otro software, hardware o dispositivo alguno.</p>

<p>DECIMA TERCERA.- CONTRATO ELECTR&Oacute;NICO.<br />
El presente contrato est&aacute; hecho constar en un mensaje de datos en t&eacute;rminos del art&iacute;culo ochenta y nueve del C&oacute;digo de Comercio, por lo que de conformidad con el art&iacute;culo ochenta y nueve bis del mismo ordenamiento no podr&aacute; neg&aacute;rsele validez alguna por el simple hecho de hacerse constar en un mensaje de datos.<br />
Las partes acuerdan que el presente mensaje de datos contiene una oferta no vinculante ni creadora de obligaciones, toda vez que la misma est&aacute; formulada al p&uacute;blico en general sin estar determinado alg&uacute;n destinatario o aceptante, por lo que los derechos y obligaciones contenidas en el presente contrato comenzaran en su vigencia a partir de la voluntad de &ldquo;EL CLIENTE&rdquo; en &ldquo;aceptar las obligaciones contenidas en el presente&rdquo; y de que se cumplan correctamente con todas las condiciones suspensivas establecidas en el presente documento.</p>

<p>DECIMA CUARTA.- LIMITANTE DE RESPONSABILIDAD.</p>

<p>Es voluntad de las partes que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; &uacute;nicamente ser&aacute; responsable por lo expresamente acordado en este contrato, por lo que en ning&uacute;n tiempo ser&aacute; responsable por cualquier uso espec&iacute;fico que se le d&eacute; al sitio web y aplicativos, por parte de &ldquo;EL CLIENTE&rdquo; o de terceros.<br />
Hasta el m&aacute;ximo permitido por las leyes aplicables, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; no ser&aacute; responsable, en ning&uacute;n caso, por da&ntilde;os directos, especiales, incidentales, indirectos, o consecuenciales que en cualquier forma se deriven o se relacionen con:<br />
a) El uso o ejecuci&oacute;n de los aplicativos y sitio www.easytaxes.com.mx, con el retraso o la falta de disponibilidad de uso de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.<br />
c) La actualizaci&oacute;n o falta de actualizaci&oacute;n de la informaci&oacute;n.<br />
d) La alteraci&oacute;n o modificaci&oacute;n, total o parcial, de la informaci&oacute;n despu&eacute;s de haber sido incluida en dicho sitio.<br />
e) Cualquier otro aspecto o caracter&iacute;stica de la informaci&oacute;n contenida o publicada en la p&aacute;gina web o a trav&eacute;s de las ligas que eventualmente se incluyan en este sitio.<br />
f) La proveedur&iacute;a o falta de proveedur&iacute;a que los dem&aacute;s servicios, todos los supuestos anteriores Ser&aacute;n vigentes, a&uacute;n en los casos en que se le hubiere notificado o avisado a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; acerca de la posibilidad de que se ocasionar&aacute;n dichos da&ntilde;os.<br />
g) Asimismo &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; tampoco ser&aacute; responsable por las opiniones o consejos que brinde su personal al cliente, en el entendido de que las mismas ser&aacute;n debidamente explicadas por &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, tampoco ser&aacute; responsable por la funcionalidad de los servicios prestados o el uso del sitio web y aplicativos y &ldquo;EL CLIENTE&rdquo; libera expresamente, en este acto, a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; en caso de que el uso del sitio web y aplicativos, origine actividades il&iacute;citas o delictivas, toda vez que el uso de los mismos es responsabilidad &uacute;nica y exclusiva de &ldquo;EL CLIENTE&rdquo; incluyendo responsabilidad frente a terceros.<br />
h) Es voluntad de las partes que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; tampoco ser&aacute; responsable de que la informaci&oacute;n que le sea otorgada por &ldquo;EL CLIENTE&rdquo; para la celebraci&oacute;n del presente contrato sea ver&iacute;dica y en caso de que &ldquo;EL CLIENTE&rdquo; haya declarado falsamente, este &uacute;ltimo ser&aacute; el &uacute;nico responsable por dicha situaci&oacute;n.<br />
i) De igual forma &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; en ning&uacute;n momento ser&aacute; responsable de que la informaci&oacute;n contenida en los CFDI que sean emitidos por &ldquo;EL CLIENTE&rdquo; a trav&eacute;s del portal del SAT o con proveedores autorizados, sea ver&iacute;dica, real, actual, o cierta, pues queda debidamente pactado que la emisi&oacute;n del CFDI es absoluta y exclusiva responsabilidad de &ldquo;EL CLIENTE&rdquo;. <br />
j) En ning&uacute;n caso &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; ser&aacute; responsable del desfase de tiempo de entrega en cualquier tipo de declaraci&oacute;n o actualizaci&oacute;n del Cliente, ya que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; depende totalmente de la respuesta del SAT (www.sat.gob.mx) y de la fecha en que el Cliente env&iacute;e su informaci&oacute;n a trav&eacute;s del sitio web y aplicativos indicados. Por lo que &ldquo;EL CLIENTE&rdquo; no podr&aacute; realizar ning&uacute;n tipo de reclamaciones a &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; deslind&aacute;ndolo desde este momento de cualquier responsabilidad.<br />
k) Asimismo &ldquo;EL CLIENTE&rdquo; manifiesta de modo expreso, que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; le ha informado previamente a la celebraci&oacute;n del presente contrato de las caracter&iacute;sticas generales de los elementos t&eacute;cnicos que han sido empleados por &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; para brindar seguridad y confidencialidad a la informaci&oacute;n proporcionada por &ldquo;EL CLIENTE&rdquo;, los cuales se encuentran en el AVISO DE PRIVACIDAD.<br />
l) Es voluntad de las partes pactar que en t&eacute;rminos del presente contrato, en correlaci&oacute;n con el sitio web y aplicativos, se le ha informado plena y completamente al cliente sobre los t&eacute;rminos, costos, condiciones, cargos adicionales y formas de pago de los servicios ofrecidos y cualquier informaci&oacute;n general o espec&iacute;fica del sitio web, aplicativos y los servicios ofrecidos, as&iacute; como el precio de pago por los mismos.<br />
m) &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; reconoce que a pesar de la alta seguridad que tienen sus sistemas, bases de datos y programas de c&oacute;mputo, es posible que cualquier persona, actuando de modo delictivo o ilegal pueda violentar la seguridad de dichos sistemas, bases de datos y programas de c&oacute;mputo y actuar en nombre de &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; sin estar facultado para ello, si ese fuere el caso &ldquo;EL CLIENTE&rdquo; libera de toda responsabilidad a &quot;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; sobre cualquier actuaci&oacute;n que realicen terceras personas, (cualquiera que sea su naturaleza), en nombre de &quot;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; y a trav&eacute;s de sus sistemas sin estar autorizado. &quot;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; dar&aacute; aviso a &ldquo;EL CLIENTE&rdquo; de dicha situaci&oacute;n en cuanto detecte la misma, lo anterior con la finalidad de que &ldquo;EL CLIENTE&rdquo; pueda tomar todas las medidas que considere pertinentes para la protecci&oacute;n de su informaci&oacute;n personal, as&iacute; como de cualquier otro derecho que pudiese ser objeto de afectaci&oacute;n.</p>

<p>DECIMA QUINTA.- EXCLUSI&Oacute;N DE GARANT&Iacute;AS Y LIMITACIONES A LA RESPONSABILIDAD.</p>

<p>Ambas partes acuerdan en que el sitio y/o app, los programas y el software o cualquier otra caracter&iacute;stica o funcionalidad se ofrecen &quot;en el estado en que se encuentran&quot;, con todas sus posibles fallas y sin garant&iacute;as de ning&uacute;n tipo. &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; no emiten declaraciones ni garant&iacute;as de ning&uacute;n tipo respecto de la suscripci&oacute;n, su calidad, el sitio y/o app, los programas y/o el software. De igual manera &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; manifiesta expresamente que no asume responsabilidad alguna por el uso de las aplicaciones, los dispositivos y el software (incluyendo la compatibilidad). Sin perjuicio de lo anterior, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; no asume responsabilidad alguna respecto de lo siguiente: (i) errores u omisiones en el sitio web y/o app o en el software; (ii) recomendaciones o asesoramiento del centro de servicio al cliente, (iii) cualquier falla o interrupci&oacute;n en la disponibilidad del sitio y/o app o el software; (iv) la provisi&oacute;n o transmisi&oacute;n de cualquier programa o software, y/o (v) cualquier p&eacute;rdida o da&ntilde;o y/o perjuicio que surja del uso del software, los programas o contenidos del sitio y/o app, incluidos los da&ntilde;os o p&eacute;rdidas causados por la descarga del software, la descarga o uso de cualquier otro software, los discos &oacute;pticos o cualquier otra conducta de los usuarios del sitio y/o app o el software. En la medida en que lo permita la legislaci&oacute;n aplicable, &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; excluyen cualquier declaraci&oacute;n o garant&iacute;a, incluyendo sin limitar, las garant&iacute;as de comerciabilidad, de calidad, de aptitud para cualquier fin en particular o de respeto de los derechos de autor. &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; tampoco declara ni garantiza que la informaci&oacute;n a la que se accede a trav&eacute;s del sitio y/o app sea precisa, completa o actualizada, ni tampoco declara ni garantiza la interrupci&oacute;n, p&eacute;rdida, corrupci&oacute;n, ataque, virus, interferencias, pirater&iacute;a inform&aacute;tica o cualquier otra intrusi&oacute;n contra la seguridad y no asume ninguna responsabilidad en relaci&oacute;n con estos hechos. La informaci&oacute;n que &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; provea en forma oral o escrita no generar&aacute; ninguna garant&iacute;a ni declaraci&oacute;n que pueda generar responsabilidad para &eacute;ste o para sus partes vinculadas.</p>

<p>En ning&uacute;n caso &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, ser&aacute; responsable (en forma individual o en su conjunto) ante &ldquo;EL CLIENTE&rdquo; por los da&ntilde;os personales o por cualquier da&ntilde;o especial, incidental, indirecto o cualquier da&ntilde;o que surgiera de la p&eacute;rdida de uso, datos o ganancias, lucro cesante o cualquier otro da&ntilde;o o p&eacute;rdida de naturaleza comercial, ya sea que se hubiera advertido o no la posibilidad del da&ntilde;o y cualquier responsabilidad que pudiera surgir con el uso de los programas, el sitio y/o app y el software, incluidos los discos &oacute;pticos, las caracter&iacute;sticas o funcionalidades. La responsabilidad total de &ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; por cualquier da&ntilde;o o p&eacute;rdida provocada por el uso del sitio y/o app, los programas y el software no podr&aacute; exceder en ning&uacute;n caso el monto de la cuota por la suscripci&oacute;n mensual correspondiente a la contrataci&oacute;n del servicio, salvo en la medida en que la legislaci&oacute;n aplicable exija lo contrario. Las limitaciones antes mencionadas se aplicar&aacute;n incluso si el resarcimiento previsto no cumple su &uacute;ltima finalidad. Si alguna autoridad competente declarara la invalidez de alguna disposici&oacute;n de esta cl&aacute;usula o de cualquier otra cl&aacute;usula de este contrato, s&oacute;lo las disposiciones declaradas inv&aacute;lidas dejar&aacute;n de ser aplicables bajo el presente contrato.</p>

<p>&ldquo;EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; no otorga ninguna declaraci&oacute;n o garant&iacute;a respecto a la compatibilidad o configuraci&oacute;n de los dispositivos, as&iacute; como respecto de su conexi&oacute;n a internet. Los distintos contratos de licencia para usuario final de software de terceros que &ldquo;EL CLIENTE&rdquo; haya acordado a fin de acceder al servicio pueden contener exclusiones adicionales o limitaciones a la responsabilidad.</p>

<p>DECIMA SEXTA.- RESCISI&Oacute;N.<br />
Es voluntad de las partes pactar que &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;, podr&aacute; dar por rescindido el presente contrato, sin necesidad de declaraci&oacute;n judicial ni administrativa para tal efecto y sin responsabilidad para &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; en los siguientes casos:<br />
a) En caso de que &ldquo;EL CLIENTE&rdquo; incumpla con cualquiera de las obligaciones que asume en el presente contrato;<br />
b) En caso de que &ldquo;EL CLIENTE&rdquo; viole alguno de los derechos de Propiedad Intelectual o Industrial de &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;;<br />
c) En caso de que &ldquo;EL CLIENTE&rdquo; no utilice el sitio web y aplicativos de conformidad con lo estipulado en el presente contrato;<br />
d) En caso de que &ldquo;EL CLIENTE&rdquo; incurra en alguna de las prohibiciones enumeradas en la cl&aacute;usula sexta, del presente contrato;<br />
e) En caso de que los datos proporcionados por &ldquo;EL CLIENTE&rdquo;, al momento del registro de su cuenta o de la activaci&oacute;n de la misma sean falsos o hayan sido declarados dolosamente en perjuicio de &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; o de terceros;<br />
f) En caso de que &ldquo;EL CLIENTE&rdquo; incurra en alg&uacute;n supuesto de suplantaci&oacute;n de identidad electr&oacute;nica, o haya utilizado datos ver&iacute;dicos pero que sean de otra persona, para contratar los servicios amparados por el presente contrato y;<br />
g) En caso de que &ldquo;EL CLIENTE&rdquo; incumpla la obligaci&oacute;n de confidencialidad que asume en la cl&aacute;usula d&eacute;cima del presente contrato.</p>

<p>DECIMA SEPTIMA.- TERMINACI&Oacute;N ANTICIPADA.<br />
Es voluntad de las partes pactar que &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; dar por terminado anticipadamente el presente contrato, mediante aviso enviado al &ldquo;EL CLIENTE&rdquo; con 15 d&iacute;as h&aacute;biles de anticipaci&oacute;n a la fecha en que opere la referida terminaci&oacute;n anticipada. Una vez que opere la terminaci&oacute;n anticipada en t&eacute;rminos del presente contrato, &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; podr&aacute; cancelar la cuenta de usuario del cliente, de conformidad con el presente contrato.<br />
DECIMA OCTAVA.- COMUNICACIONES.<br />
Es voluntad de las partes que todas las comunicaciones, entre ellos, para efectos del presente contrato, se realicen v&iacute;a correo electr&oacute;nico o mediante cualquier otro medio de comunicaci&oacute;n que &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo; facilite a trav&eacute;s del sitio web y aplicativos.<br />
DECIMA NOVENA.- CESI&Oacute;N.<br />
&ldquo;EL CLIENTE&rdquo; no podr&aacute; ceder o transmitir total o parcialmente los derechos y obligaciones derivados de este contrato, sin el previo consentimiento que por escrito otorgue &quot; EL PRESTADOR DE SERVICIOS (EASY TAXES)&rdquo;.</p>

<p>VIGESIMA.- ENCABEZADOS.<br />
Las partes convienen en que los encabezados que aparecen al inicio de cada una de las cl&aacute;usulas que conforman este contrato se han insertado &uacute;nica y exclusivamente para facilitar su lectura y manejo, motivo por el cual, no se considerar&aacute; en ning&uacute;n caso que definan o limiten las obligaciones.</p>

<p>VIGESIMA PRIMERA.- RECONOCIMIENTO CONTRACTUAL.<br />
El presente Contrato constituye el acuerdo integro entre las partes en relaci&oacute;n con su objeto y deja sin efecto cualquier otra negociaci&oacute;n, obligaci&oacute;n o comunicaci&oacute;n entre &eacute;stas, ya sea verbal o escrita, efectuada con anterioridad a la fecha en que se firme el mismo.</p>

<p>VIGESIMA SEGUNDA.- ACEPTACI&Oacute;N DE LOS TERMINOS Y CONDICIONES DEL CONTRATO.<br />
El presente contrato, incluyendo los t&eacute;rminos y condiciones de uso, rigen el uso que &ldquo;EL CLIENTE&rdquo; haga de la p&aacute;gina de internet www.easytaxes.com.mx, al igual que los aplicativos en su misma plataforma web, y dem&aacute;s softwares. Al utilizar, visitar o navegar en el Sitio y/o App, &ldquo;EL CLIENTE&rdquo; acuerda y se compromete a cumplir el presente contrato. En caso de no estar de acuerdo con el presente Contrato, no deber&aacute; utilizar la plataforma ni las aplicaciones relacionadas con la misma.</p>

<p>Por favor tome en cuenta que el presente contrato, incluyendo los t&eacute;rminos y condiciones de uso, aplica para el uso que &ldquo;EL CLIENTE&rdquo; haga del sitio y plataforma web, aplicaciones y dem&aacute;s softwares; sin embargo, es posible que si &ldquo;EL CLIENTE&rdquo; desea consultar el presente contrato y los t&eacute;rminos de uso, as&iacute; como nuestro aviso de privacidad, tenga que hacerlo directamente en nuestro sitio.</p>

<p>VIGECIMA TERCERA.- JURISDICCI&Oacute;N.<br />
Para la interpretaci&oacute;n y cumplimiento del presente contrato, as&iacute; como para todo lo no previsto en el mismo, las partes aceptan en com&uacute;n acuerdo en someterse a la jurisdicci&oacute;n de los Tribunales Locales y/o Federales del Estado de Jalisco, por lo que renuncian al fuero que por raz&oacute;n de su domicilio presente o futuro pudiera corresponderles.<br />
Le&iacute;do que fue el presente instrumento y enteradas las partes de su contenido y alcances, lo firman por duplicado, en la ciudad de Zapopan Jalisco, a la fecha en que se contrata el servicio descrito en este documento.<br />
El Cliente declara que ha le&iacute;do y aceptado los t&eacute;rminos y condiciones establecidos en el presente mensaje de datos y que es su voluntad obligase por virtud del mismo, manifestando que acepta el presente contrato con el uso del sitio web y aplicativos, por tal virtud acepta de conformidad todos los t&eacute;rminos establecidos en el presente Contrato. El uso o acceso continuado de &ldquo;EL CLIENTE&rdquo; al sitio web o aplicativos significar&aacute; la aceptaci&oacute;n por parte del mismo de cualquier cambio en este Contrato.</p>

<p></p>
